name: FruitbotChat
version: 1.0.2
main: com.benkearns.fruitbotchat.FruitbotChat
api-version: '1.20'
description: Private-message chatbot for server guidance compatible with Essentials PM
author: Ben Kearns
commands:
  fruitbotchat:
    description: Enable or disable Fruitbot replies
    usage: /fruitbotchat <enable|disable>
    permission: fruitbotchat.admin
    permission-message: "You don't have permission to manage Fruitbot."
permissions:
  fruitbotchat.use:
    description: Allows players to use FruitBot
    default: true
  fruitbotchat.admin:
    description: Allows access to admin commands
    default: op
